-- Dados de perfil da companhia
create table public.company_profile (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  cpf_cnpj text not null,
  address text not null,
  zip_code text not null,
  city text not null,
  state text not null,
  country text not null,
  responsible_name text not null,
  phone text not null,
  language text not null,
  constraint company_profile_pkey primary key (id),
  constraint company_profile_id_key unique (id)
) TABLESPACE pg_default;

-- Cria a tabela de company
create table public.company (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null,
  company_name text null,
  company_profile_id bigint null,
  profile_complete boolean not null default false,
  constraint company_pkey primary key (id),
  constraint company_id_key unique (id),
  constraint company_user_id_key unique (user_id),
  constraint company_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE,
  constraint company_profile_id_key unique (company_profile_id),
  constraint company_profile_id_fkey foreign KEY (company_profile_id) references company_profile (id)
) TABLESPACE pg_default;

-- Cria tabela de pagamentos
create table public.payments (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  company_id bigint null,
  amount numeric(18, 2) not null default '0'::numeric,
  status public.status_payment not null default 'pendente'::status_payment,
  paid_in timestamp with time zone null,
  due_date timestamp with time zone not null,
  reference text not null default '-'::text,
  asaas_id text null,
  payment_link text null,
  constraint payments_pkey primary key (id),
  constraint payments_company_id_fkey foreign KEY (company_id) references company (id)
) TABLESPACE pg_default;


-- Enum para tipos de agente
create type public.agent_type as enum ('agendamento', 'sdr', 'suporte');

-- Tabela de agentes de IA
create table public.agents (
  id uuid not null default gen_random_uuid (),
  name text not null,
  type public.agent_type not null,
  is_active boolean not null default false,
  created_at timestamp with time zone not null default now(),
  company_id bigint not null,
  constraint agents_pkey primary key (id),
  constraint agents_company_id_fkey foreign key (company_id) references company (id)
) TABLESPACE pg_default;

