export const MAX_PIPELINES_PER_COMPANY = 5
export const MAX_STAGES_PER_PIPELINE = 10

export const PIPELINE_NAME_MAX_LENGTH = 60
export const PIPELINE_DESCRIPTION_MAX_LENGTH = 240
export const STAGE_NAME_MAX_LENGTH = 40

export const CARD_CONTACT_MAX_LENGTH = 120
